### ISSUE TITLE
Codefresh Example

### ISSUE THREAD

**Issue by userbradley** [dineshba/tf-summarize#29]
Howdy,

I use codefresh and thought I would post an example here and if you think it's useful, I can open a PR

The below makes the assumption that you have already done a terraform init etc, and are logged in to your cloud provider of choice.

I have had to use the output to json as the `tfplan` file was not being picked up, and also allows you to use the `output.json` in other places as we only create it once.

```yaml
version: "1.0"

stages:
  - "plan"
  - "summarize"

  TerraformPlan:
    image: hashicorp/terraform:1.3.8
    title: Terraform Plan
    stage: plan
    working_directory: "${{clone}}/"
    commands:
      - terraform plan -out=tfplan
      - terraform show -json tfplan > output.json
  
  tfSummarize:
    image: europe-west2-docker.pkg.dev/<>/devops/tf-summarize:latest
    title: Show Changes
    stage: summarize
    working_directory: "${{clone}}"
    commands:
      - tf-summarize output.json
```

Let me know if you want a PR opened for this, as I think showing how it can be used in CI would be awesome.
