### ISSUE TITLE
Use idiomatic `.tar.gz` archive format for linux & darwin artifacts

### ISSUE THREAD

**Issue by stevehipwell** [dineshba/tf-summarize#52]
Firstly, thanks for a great project.

It looks like your GoReleaser config is setting all archives to `.zip` format instead of just the Windows archives as would be idiomatic. This means that additional tools need to be installed and non-standard patterns need to be used to install this on a Linux machine.

My suggestion would be to change the archive configuration from:

```yaml
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
```

To:

```yaml
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
```
